config/routes.rb
Store3::Application.routes.draw do
  resources :bookstores

  resources :books

  

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @error="www"
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title)
    end
end

app/controllers/bookstores_controller.rb
class BookstoresController < ApplicationController
  before_action :set_bookstore, only: [:show, :edit, :update, :destroy]

  # GET /bookstores
  # GET /bookstores.json
  def index
    p "WWWWW"
    @bookstores = Bookstore.all
  end

  # GET /bookstores/1
  # GET /bookstores/1.json
  def show
  end

  # GET /bookstores/new
  def new
    @bookstore = Bookstore.new
  end

  # GET /bookstores/1/edit
  def edit
  end

  # POST /bookstores
  # POST /bookstores.json
  def create
    @bookstore = Bookstore.new(bookstore_params)

    respond_to do |format|
      if @bookstore.save
        format.html { redirect_to :action => :index, notice: 'Bookstore was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bookstore }
      else
        format.html { render action: 'new' }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookstores/1
  # PATCH/PUT /bookstores/1.json
  def update
    respond_to do |format|
      if @bookstore.update(bookstore_params)
        format.html { redirect_to :action => :index, notice: 'Bookstore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstores/1
  # DELETE /bookstores/1.json
  def destroy
    p "destroy    ddddddd"
    @bookstore.destroy
    #respond_to do |format|
    #  format.html { redirect_to :action => :index }
    #  format.json { head :no_content }
    #end
    #redirect_to :action => :index,:method => :get
    @bookstores = Bookstore.all
    render :action => :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookstore
      @bookstore = Bookstore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookstore_params
      params.require(:bookstore).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<script type="text/javascript">
    $(function(){
      $('#bookstore').click(function(event){
          $('#modal_dialog').dialog({
              width: 600,
              height: 150,
              autoOpen: true,
              modal: true//,
              //drag: function(event) {
              //    //$.get(<%= url_for :action => :index %>)
              //    window.location.href = <%= url_for :action => :index %>;
              //}

              //show: 'bounce',
              //hide: 'explode',

          }).dialog('open');

          $('#modal_dialog').dialog({
              close: function(event) {
                  window.location.href = '<%= url_for :action => :index %>';

              }
          });

      });

    });
</script>
<div id="modal_dialog"></div>
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
<%= link_to 'bookstore',bookstores_path,:remote => true ,:id=>:bookstore%>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/bookstores/_edit.html.erb
<h1>Editing bookstore</h1>

<%= render 'form2' %>

<%= link_to 'Show', @bookstore ,:remote => true%> |
<%= link_to 'Back', bookstores_path,:remote => true %>

app/views/bookstores/_form.html.erb
<%= form_for(@bookstore) do |f| %>
  <% if @bookstore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookstore.errors.count, "error") %> prohibited this bookstore from being saved:</h2>

      <ul>
      <% @bookstore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookstores/_form2.html.erb
<%= form_for(@bookstore,:remote => true) do |f| %>
  <% if @bookstore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookstore.errors.count, "error") %> prohibited this bookstore from being saved:</h2>

      <ul>
      <% @bookstore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookstores/_index.html.erb
<h1>Listing bookstores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookstores.each do |bookstore| %>
      <tr>
        <td><%= bookstore.name %></td>
        <td><%= link_to 'Show', bookstore,:remote => true %></td>
        <td><%= link_to 'Edit', edit_bookstore_path(bookstore) ,:remote => true%></td>
        <td><%= link_to 'Destroy', bookstore,:remote => true, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookstore', new_bookstore_path ,:remote => true%>

app/views/bookstores/_new.html.erb
<h1>New bookstore</h1>

<%= render 'form2' %>

<%= link_to 'Back', bookstores_path,:remote => true %>

app/views/bookstores/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bookstore.name %>
</p>

<%= link_to 'Edit', edit_bookstore_path(@bookstore),:remote => true %> |
<%= link_to 'Back', bookstores_path,:remote => true %>

app/views/bookstores/edit.html.erb
<h1>Editing bookstore</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookstore %> |
<%= link_to 'Back', bookstores_path %>

app/views/bookstores/edit.js.erb
$('#modal_dialog').html('<%= escape_javascript(render  'edit') %>');

app/views/bookstores/index.html.erb
<h1>Listing bookstores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookstores.each do |bookstore| %>
      <tr>
        <td><%= bookstore.name %></td>
        <td><%= link_to 'Show', bookstore %></td>
        <td><%= link_to 'Edit', edit_bookstore_path(bookstore) %></td>
        <td><%= link_to 'Destroy', bookstore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookstore', new_bookstore_path %>

app/views/bookstores/index.js.erb
$('#modal_dialog').html('<%= escape_javascript(render  'index') %>');

app/views/bookstores/new.html.erb
<h1>New bookstore</h1>

<%= render 'form' %>

<%= link_to 'Back', bookstores_path %>

app/views/bookstores/new.js.erb
$('#modal_dialog').html('<%= escape_javascript(render  'new') %>');

app/views/bookstores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bookstore.name %>
</p>

<%= link_to 'Edit', edit_bookstore_path(@bookstore) %> |
<%= link_to 'Back', bookstores_path %>

app/views/bookstores/show.js.erb
$('#modal_dialog').html('<%= escape_javascript(render  'show') %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store3</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>